---
- block:
    - name: Create Vagrantfile from template.
      template:
        src: "Vagrantfile.j2"
        dest: "{{ role_path }}/files/Vagrantfile"

    - name: Bring Vagrant host up.
      command:
        cmd: "vagrant up"
        chdir: "{{ role_path }}/files"

    - name: Add new host to inventory.
      add_host:
        host: "{{ ipv4_address }}"
        groups: vagrant
        ansible_user: vagrant
        ansible_ssh_private_key_file: "{{ role_path }}/files/.vagrant/machines/{{ hostname }}/virtualbox/private_key"
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"

  # - name: Add newly deployed host to /etc/hosts.
  #   lineinfile:
  #     state: present
  #     path: /etc/hosts
  #     regex: "^.*{{ hostname }}"
  #     line: "{{ ipv4_address }} {{ hostname }}"
  #   become: true

  rescue:
    - name: Destroy Vagrant host.
      command:
        cmd: "vagrant destroy --force --parallel"
        chdir: "{{ role_path }}/files"
