---
- name: Deploy Kali Linux on Digital Ocean.
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - ssh-check
    - digitalocean/kali

- name: Initialize Kali Linux.
  hosts: do
  remote_user: root
  roles:
    - init
