---
# main task file for configuration/wireguard/client role
- name: Configuring Wireguard client node
  import_tasks: client.yml
  become: true

- name: Configuring Wireguad master node
  import_tasks: master.yml
  become: true

- name: Configuring preshared keys
  import_tasks: psk.yml
  become: true
