---

- name: Configuring Wireguard peer conf
  blockinfile:
    path: "/etc/wireguard/peers/{{ ansible_hostname }}.conf"
    marker: "{mark}"
    marker_begin: "# {{ ansible_hostname }} begin"
    marker_end: "# {{ ansible_hostname }} end"
    create: yes
    block: |
      [Peer]
      PublicKey = {{ local_node_pubkey }}
      AllowedIPs = {{ wg_ip }}/32

- name: Configuring Wireguad master conf
  lineinfile:
    path: "/etc/wireguard/wg0.conf"
    state: present
    line: PostUp = wg addconf wg0 /etc/wireguard/peers/{{ ansible_hostname }}.conf

- name: Restarting Wireguard interface
  shell:
    cmd: "wg-quick down wg0 && wg-quick up wg0"
  ignore_errors: true

