---
- block: 
  - name: Configuring Wireguad master node
    blockinfile:
      path: "/etc/wireguard/peers/{{ inventory_hostname_short }}.conf"
      marker: "{mark}"
      marker_begin: "# ANSIBLE MANAGED BLOCK BEGIN"
      marker_end: "# ANSIBLE MANAGED BLOCK END"
      create: yes
      block: |
        [Peer]
        PublicKey = {{ node_pubkey }}
        AllowedIPs = {{ wg_ip }}
        PersistentKeepalive = 25

  - name: Restarting Wireguard interface
    command:
      cmd: "wg-quick down wg0 && wg-quick up wg0"
  delegate_to: "{{ hostvars['wg_master_node']['ansible_host'] }}"
  become: true
