---
# - name: Remove existing Droplet.
#   digital_ocean_droplet:
#     state: absent
#     name: kali-test
#     unique_name: yes


# - name: Wait for the Droplet to be removed
#   pause:
#     seconds: 10

- name: Create new Droplet.
  digital_ocean_droplet:
    state: present
    name: "{{ hostname }}"
    unique_name: yes
    private_networking: yes
    size: c-2
    image_id: "104051903"
    region: ams3
    # Customize this for your account.
    ssh_keys:
      - d2:50:66:64:37:12:d1:4f:59:0e:27:c8:e0:08:68:f9
    monitoring: yes

  register: do

- name: Add new host to inventory.
  add_host:
    host: "{{ do.data.ip_address }}"
    ansible_host: "{{ hostname }}"
    groups: digitalocean
    ansible_user: root
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
  when: do.data is defined
  changed_when: False

- name: Add newly deployed host to /etc/hosts.
  lineinfile:
    state: present
    path: /etc/hosts
    regex: "^.*{{ hostname }}"
    line: "{{ do.data.ip_address }} {{ hostname }}"
  become: true

- name: Wait for host to become reachable.
  wait_for_connection:
    delay: 10

# Necessary else further roles will not work
# - name: Wait for the host to become reachable.
#   pause:
#     seconds: 10