---
# - name: Purge existing locales
#   locale_gen:
#     name: "*"
#     state: absent

- name: Set up locale.
  locale_gen:
    name: en_US.UTF-8
    state: present


# Debugging hash mismatch
# - name: Debugging hash mismatch
#   file:
#     dest: /etc/gcrypt
#     state: directory

# - name: Debugging hash mismatch
#   file:
#     dest: /etc/gcrypt/hwf.deny
#     state: touch

# - name: Removing existing sources.list
#   file:
#     path: /etc/apt/sources.list
#     state: absent
      

- name: Ensuring that Debian Bullseye backport repositories are present in sources.list
  lineinfile:
    path: "/etc/apt/sources.list"
    state: present
    create: yes
    line: "{{ item }}"
  with_items:
  - deb http://deb.debian.org/debian bullseye-backports main
  - deb-src http://deb.debian.org/debian bullseye-backports main


- name: Updating package cache.
  apt:
    cache_valid_time: 3600
    update_cache: yes

    
- name: Performing distribution upgrade.
  apt:
    upgrade: dist
  tags:
    - slow

- name: Install basic system packages
  apt:
    name: "{{ packages_debian_default }}"
    state: latest


- name: Install additional system packages
  apt:
    name: "{{ packages_debian_additional }}"
    state: latest
  tags:
    - slow

# - name: Copy unattended-upgrades configuration files in place.
#   template:
#     src: "../templates/{{ item }}.j2"
#     dest: "/etc/apt/apt.conf.d/{{ item }}"
#     owner: root
#     group: root
#     mode: 0644
#   with_items:
#     - 20auto-upgrades
#     - 50unattended-upgrades
