---
- name: Installing default Debian packages.
  apt:
    name: "{{ packages_debian }}"
    state: latest

- name: Installing default Kali Linux packages.
  apt:
    name: "{{ packages_kali }}"

- name: Configure XRDP.
  replace:
    path: /etc/xrdp/xrdp.ini
    regexp: "^.*port="
    replace: "port={{ xrdp_port }}"

- name: Enabling XRDP systemd service.
  service:
    name: xrdp
    state: started
    enabled: yes

- name: Printing XRDP connection settings.
  debug:
    msg: |
      {{ inventory_hostname }}:{{ xrdp_port }}
