---
# - name: Purge existing locales
#   locale_gen:
#     name: "*"
#     state: absent

- name: Set up locale.
  locale_gen:
    name: en_US.UTF-8
    state: present

# Debugging hash mismatch
# - name: Debugging hash mismatch
#   file:
#     dest: /etc/gcrypt
#     state: directory

# - name: Debugging hash mismatch
#   file:
#     dest: /etc/gcrypt/hwf.deny
#     state: touch

- name: Update package cache and upgrade system.
  apt:
    cache_valid_time: 3600
    upgrade: dist

- name: Install basic system packages
  apt:
    name: "{{ packages_debian }}"
    state: latest

- name: Copy unattended-upgrades configuration files in place.
  template:
    src: "../templates/{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 20auto-upgrades
    - 50unattended-upgrades
