---
# - name: Purge existing locales
#   locale_gen:
#     name: "*"
#     state: absent

- name: Set up locale.
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Updating package cache.
  apt:
    cache_valid_time: 3600
    update_cache: yes

    
- name: Performing distribution upgrade.
  apt:
    upgrade: dist
  tags:
    - slow

- name: Install basic system packages
  apt:
    name: "{{ packages_debian_default }}"
    state: latest

- name: Installing default Kali Linux packages.
  apt:
    name: "{{ packages_kali }}"
  tags:
    - slow

- name: Configure XRDP.
  replace:
    path: /etc/xrdp/xrdp.ini
    regexp: "^.*port="
    replace: "port={{ xrdp_port }}"

- name: Enabling XRDP systemd service.
  service:
    name: xrdp
    state: started
    enabled: yes

- name: Printing XRDP connection settings.
  debug:
    msg: |
      {{ inventory_hostname }}:{{ xrdp_port }}
