---
packages:
    - net-tools 
    - tree 
    - git
    - rsync
    - zsh
    - tmux
    - vim
    - curl
    - wget
    - git
    - htop
    - speedtest-cli
    - iperf
packages_kali:
    #- kali-linux-large
    #- kali-desktop-xfce
    - xorg
    - xrdp
xrdp_port: "3390"
ansible_python_interpreter: "/usr/bin/python3"