---
- block:
    - name: Creating Vagrantfile
      template:
        src: "{{ role_path }}/{{ vagrantfile_src }}"
        dest: "{{ role_path }}/files/Vagrantfile"

    - name: Bringing Vagrant host up
      command:
        cmd: "vagrant up"
        chdir: "{{ role_path }}/files"

    - name: Adding new host to the Ansible inventory
      add_host:
        host: "{{ ipv4_address }}"
        groups: vagrant
        ansible_user: vagrant
        ansible_ssh_private_key_file: "{{ role_path }}/files/.vagrant/machines/{{ hostname }}/virtualbox/private_key"
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    
    - name: Adding Vagrant hosts's ssh key to ssh agent.
      shell:
        cmd: "ssh-add {{ role_path }}/files/.vagrant/machines/{{ hostname }}/virtualbox/private_key"
        
  # - name: Add newly deployed host to /etc/hosts.
  #   lineinfile:
  #     state: present
  #     path: /etc/hosts
  #     regex: "^.*{{ hostname }}"
  #     line: "{{ ipv4_address }} {{ hostname }}"
  #   become: true

  rescue:
    - name: Destroying Vagrant host.
      command:
        cmd: "vagrant destroy --force --parallel"
        chdir: "{{ role_path }}/files"
