---
- name: Deploy on the local machine using Vagrant.
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - { role: deployment/digitalocean/debian, do_droplet_hostname: debian }

- name: Initalize host.
  hosts: do
  roles:
    - setup/init
    - { role: configuration/wireguard/client, wg_ip: 192.168.3.17 }