---
- name: Deploying Debian on Digital Ocean.
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - { role: deployment/digitalocean/debian, do_droplet_hostname: debian-kali }

- name: Initialize Debian.
  hosts: do
  remote_user: root
  roles:
    - setup/init
    - { role: configuration/wireguard/client, wg_ip: 192.168.3.18 }

