---
- name: Deploy Kali Linux on Digital Ocean.
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - { role: deployment/digitalocean/debian, do_droplet_hostname: kali }

- name: Initialize Kali Linux.
  hosts: digitalocean
  remote_user: root
  roles:
    - setup/init
