---
- name: Deploy Kali Linux on Digital Ocean.
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - deployment/digitalocean/kali

- name: Initialize Kali Linux.
  hosts: digitalocean
  remote_user: root
  roles:
    - setup/init
