---
- name: Set default Git branch name
  git_config:
    scope: global
    name: init.defaultBranch
    value: main

- name: Set up Z shell (zsh)
  include_tasks: zsh.yml

- name: Install tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_user_dir }}/.tmux/plugins/tpm"
    update: no

- name: Update remote environment settings
  copy:
    src: files/
    dest: "{{ ansible_user_dir }}/"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0640'
    local_follow: yes
    force: yes

- name: Create .localrc
  file:
    state: touch
    path: "{{ ansible_user_dir}}/.localrc"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0740'

- name: Set hostname variable in .localrc
  lineinfile:
    path: "{{ ansible_user_dir}}/.localrc"
    regexp: '^HOSTNAME'
    line: "export HOSTNAME={{ ansible_hostname }}"
    state: present
    